const Home = () => {
    return (
        <div className="row">
            <div className="col s10 offset-s1 l6 offset-l3">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste labore incidunt rem doloremque earum amet voluptas ipsam eius fuga magnam ea, maiores esse error libero ut, aliquam quisquam harum?Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos quisquam recusandae incidunt dolorem rerum dolorum doloremque autem minus, modi corporis aspernatur ex sit cupiditate. Totam facere deserunt pariatur consequatur maiores?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, tenetur amet eos suscipit cupiditate cum quod distinctio ea fuga quos culpa excepturi odio necessitatibus voluptatem facilis qui reiciendis ipsum expedita. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed deserunt quia repellendus, voluptatibus quod et quis id exercitationem qui omnis quam vero commodi perferendis nam quo. A sapiente odit delectus.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste labore incidunt rem doloremque earum amet voluptas ipsam eius fuga magnam ea, maiores esse error libero ut, aliquam quisquam harum?Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos quisquam recusandae incidunt dolorem rerum dolorum doloremque autem minus, modi corporis aspernatur ex sit cupiditate. Totam facere deserunt pariatur consequatur maiores?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, tenetur amet eos suscipit cupiditate cum quod distinctio ea fuga quos culpa excepturi odio necessitatibus voluptatem facilis qui reiciendis ipsum expedita. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed deserunt quia repellendus, voluptatibus quod et quis id exercitationem qui omnis quam vero commodi perferendis nam quo. A sapiente odit delectus.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste labore incidunt rem doloremque earum amet voluptas ipsam eius fuga magnam ea, maiores esse error libero ut, aliquam quisquam harum?Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos quisquam recusandae incidunt dolorem rerum dolorum doloremque autem minus, modi corporis aspernatur ex sit cupiditate. Totam facere deserunt pariatur consequatur maiores?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, tenetur amet eos suscipit cupiditate cum quod distinctio ea fuga quos culpa excepturi odio necessitatibus voluptatem facilis qui reiciendis ipsum expedita. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed deserunt quia repellendus, voluptatibus quod et quis id exercitationem qui omnis quam vero commodi perferendis nam quo. A sapiente odit delectus.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste labore incidunt rem doloremque earum amet voluptas ipsam eius fuga magnam ea, maiores esse error libero ut, aliquam quisquam harum?Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos quisquam recusandae incidunt dolorem rerum dolorum doloremque autem minus, modi corporis aspernatur ex sit cupiditate. Totam facere deserunt pariatur consequatur maiores?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, tenetur amet eos suscipit cupiditate cum quod distinctio ea fuga quos culpa excepturi odio necessitatibus voluptatem facilis qui reiciendis ipsum expedita. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed deserunt quia repellendus, voluptatibus quod et quis id exercitationem qui omnis quam vero commodi perferendis nam quo. A sapiente odit delectus.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste labore incidunt rem doloremque earum amet voluptas ipsam eius fuga magnam ea, maiores esse error libero ut, aliquam quisquam harum?Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos quisquam recusandae incidunt dolorem rerum dolorum doloremque autem minus, modi corporis aspernatur ex sit cupiditate. Totam facere deserunt pariatur consequatur maiores?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, tenetur amet eos suscipit cupiditate cum quod distinctio ea fuga quos culpa excepturi odio necessitatibus voluptatem facilis qui reiciendis ipsum expedita. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed deserunt quia repellendus, voluptatibus quod et quis id exercitationem qui omnis quam vero commodi perferendis nam quo. A sapiente odit delectus.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iste labore incidunt rem doloremque earum amet voluptas ipsam eius fuga magnam ea, maiores esse error libero ut, aliquam quisquam harum?Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos quisquam recusandae incidunt dolorem rerum dolorum doloremque autem minus, modi corporis aspernatur ex sit cupiditate. Totam facere deserunt pariatur consequatur maiores?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, tenetur amet eos suscipit cupiditate cum quod distinctio ea fuga quos culpa excepturi odio necessitatibus voluptatem facilis qui reiciendis ipsum expedita. Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed deserunt quia repellendus, voluptatibus quod et quis id exercitationem qui omnis quam vero commodi perferendis nam quo. A sapiente odit delectus.</p>
            </div>    
        </div>
         );
}
 
export default Home;